### ISSUE TITLE
Java3d error on Draw module

### ISSUE THREAD

**Issue by Strauteka** [Strauteka/3d-bin-space-utilization#1]
Java3d error on Draw module 
java 17
windows 10
```
java.lang.IllegalAccessError: class javax.media.j3d.Win32NativeConfigTemplate3D (in unnamed module @0x1a4555f8) cannot access class sun.awt.Win32GraphicsConfig (in module java.desktop) because module java.desktop does not export sun.awt to unnamed module @0x1a4555f8
        at javax.media.j3d.Win32NativeConfigTemplate3D.getBestConfiguration(Win32NativeConfigTemplate3D.java:57)
        at javax.media.j3d.NativePipeline.getBestConfiguration(NativePipeline.java:3296)
        at javax.media.j3d.Renderer.doWork(Renderer.java:495)
        at javax.media.j3d.J3dThread.run(J3dThread.java:256)
```
__Runs on java 11__
For development preview please use java 1.8 or java 11. Java3d is Old library and best solution would me migrate to Ardor3D or similar library for java 17.

**Comment by zzw-dream** [comment]
no j3dcore-ogl-chk in java.library.path
java 1.8
Windows 10

No error is reported, but execute Java - jar \demo\target\demo-jar-with-dependencies. Jar reported an error. Why!

` java.lang.UnsatisfiedLinkError: no j3dcore-ogl-chk in java.library.path
Exception in thread "main" java.lang.UnsatisfiedLinkError: no j3dcore-d3d in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at javax.media.j3d.NativePipeline$1.run(NativePipeline.java:189)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.media.j3d.NativePipeline.loadLibrary(NativePipeline.java:180)
        at javax.media.j3d.NativePipeline.loadLibraries(NativePipeline.java:137)
        at javax.media.j3d.MasterControl.loadLibraries(MasterControl.java:948)
        at javax.media.j3d.VirtualUniverse.<clinit>(VirtualUniverse.java:280)
        at org.strauteka.jbin.draw3d.Draw3d.<init>(Draw3d.java:79)
        at org.strauteka.jbin.draw3d.Draw3d.draw(Draw3d.java:468)
`
